AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  amiId:
    Description: region specific image from the parameter store
    Type: 'String'
    Default: 'ami-0b59bfac6be064b78'

  TargetGroupArn:
    Description: ARN of target group to register ASG 
    Type: 'String'

Resources:
  webappLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !Ref amiId
        InstanceType: t3.large
        KeyName: trane-demo-keypair

        # https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html
        UserData:  
          'Fn::Base64': !Sub |
            #!/bin/bash
            sudo su
            yum -y install httpd
            instace_id=$(curl 169.254.169.254/latest/meta-data/instance-id)
            echo "<p>Hello from $instance_id </p>" >> /var/www/html/index.html
            sudo systemctl enable httpd
            sudo systemctl start httpd
  webappASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref webappLaunchTemplate
        Version: !GetAtt webappLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroupArn
      VPCZoneIdentifier: 
        - subnet-3648f85f
